package events
import "errors"
var (
	ErrEventTypeRequired = errors.New("event type is required")
	ErrInvalidEventPayload = errors.New("invalid event payload")
	ErrEventNotFound = errors.New("event not found")
	ErrEventAlreadyProcessed = errors.New("event already processed")
	ErrInvalidEventFormat = errors.New("invalid event format")
	ErrEventProcessingFailed = errors.New("event processing failed")
	ErrArticleNotFound = errors.New("article not found")
	ErrUserNotFound = errors.New("user not found")
	ErrCommentNotFound = errors.New("comment not found")
	ErrCategoryNotFound = errors.New("category not found")
	ErrUnauthorizedAction = errors.New("unauthorized action")
	ErrInvalidArticleStatus = errors.New("invalid article status")
	ErrInvalidUserRole = errors.New("invalid user role")
	ErrInvalidCommentStatus = errors.New("invalid comment status")
	ErrDuplicateEvent = errors.New("duplicate event")
	ErrEventValidationFailed = errors.New("event validation failed")
	ErrInvalidEventActor = errors.New("invalid event actor")
	ErrInvalidEventTimestamp = errors.New("invalid event timestamp")
	ErrEventSerializationFailed = errors.New("event serialization failed")
	ErrEventDeserializationFailed = errors.New("event deserialization failed")
	ErrInvalidEventAggregateID = errors.New("invalid event aggregate ID")
	ErrEventRetryLimitExceeded = errors.New("event retry limit exceeded")
	ErrInvalidEventMetadata = errors.New("invalid event metadata")
	ErrEventPublishFailed = errors.New("event publish failed")
	ErrEventConsumeFailed = errors.New("event consume failed")
	ErrInvalidEventHandler = errors.New("invalid event handler")
	ErrEventHandlerNotFound = errors.New("event handler not found")
	ErrEventTopicNotFound = errors.New("event topic not found")
	ErrInvalidEventTopic = errors.New("invalid event topic")
	ErrEventConnectionFailed = errors.New("event connection failed")
	ErrEventTimeoutExceeded = errors.New("event timeout exceeded")
) 