// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// UserInternalServiceClient is the client API for UserInternalService service.
type UserInternalServiceClient interface {
	GetUserBasic(ctx context.Context, in *GetUserBasicRequest, opts ...grpc.CallOption) (*UserBasicResponse, error)
	GetUsersByIDs(ctx context.Context, in *GetUsersByIDsRequest, opts ...grpc.CallOption) (*UsersResponse, error)
	CheckUserStatus(ctx context.Context, in *CheckUserStatusRequest, opts ...grpc.CallOption) (*UserStatusResponse, error)
	GetSellerInfo(ctx context.Context, in *GetSellerInfoRequest, opts ...grpc.CallOption) (*SellerInfoResponse, error)
}

type userInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserInternalServiceClient(cc grpc.ClientConnInterface) UserInternalServiceClient {
	return &userInternalServiceClient{cc}
}

func (c *userInternalServiceClient) GetUserBasic(ctx context.Context, in *GetUserBasicRequest, opts ...grpc.CallOption) (*UserBasicResponse, error) {
	out := new(UserBasicResponse)
	err := c.cc.Invoke(ctx, "/user.UserInternalService/GetUserBasic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInternalServiceClient) GetUsersByIDs(ctx context.Context, in *GetUsersByIDsRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, "/user.UserInternalService/GetUsersByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInternalServiceClient) CheckUserStatus(ctx context.Context, in *CheckUserStatusRequest, opts ...grpc.CallOption) (*UserStatusResponse, error) {
	out := new(UserStatusResponse)
	err := c.cc.Invoke(ctx, "/user.UserInternalService/CheckUserStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInternalServiceClient) GetSellerInfo(ctx context.Context, in *GetSellerInfoRequest, opts ...grpc.CallOption) (*SellerInfoResponse, error) {
	out := new(SellerInfoResponse)
	err := c.cc.Invoke(ctx, "/user.UserInternalService/GetSellerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInternalServiceServer is the server API for UserInternalService service.
type UserInternalServiceServer interface {
	GetUserBasic(context.Context, *GetUserBasicRequest) (*UserBasicResponse, error)
	GetUsersByIDs(context.Context, *GetUsersByIDsRequest) (*UsersResponse, error)
	CheckUserStatus(context.Context, *CheckUserStatusRequest) (*UserStatusResponse, error)
	GetSellerInfo(context.Context, *GetSellerInfoRequest) (*SellerInfoResponse, error)
	mustEmbedUnimplementedUserInternalServiceServer()
}

// UnimplementedUserInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserInternalServiceServer struct{}

func (UnimplementedUserInternalServiceServer) GetUserBasic(context.Context, *GetUserBasicRequest) (*UserBasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBasic not implemented")
}
func (UnimplementedUserInternalServiceServer) GetUsersByIDs(context.Context, *GetUsersByIDsRequest) (*UsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersByIDs not implemented")
}
func (UnimplementedUserInternalServiceServer) CheckUserStatus(context.Context, *CheckUserStatusRequest) (*UserStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserStatus not implemented")
}
func (UnimplementedUserInternalServiceServer) GetSellerInfo(context.Context, *GetSellerInfoRequest) (*SellerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSellerInfo not implemented")
}
func (UnimplementedUserInternalServiceServer) mustEmbedUnimplementedUserInternalServiceServer() {}

// UnsafeUserInternalServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeUserInternalServiceServer interface {
	mustEmbedUnimplementedUserInternalServiceServer()
}

func RegisterUserInternalServiceServer(s grpc.ServiceRegistrar, srv UserInternalServiceServer) {
	s.RegisterService(&UserInternalService_ServiceDesc, srv)
}

func _UserInternalService_GetUserBasic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBasicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInternalServiceServer).GetUserBasic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserInternalService/GetUserBasic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInternalServiceServer).GetUserBasic(ctx, req.(*GetUserBasicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInternalService_GetUsersByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInternalServiceServer).GetUsersByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserInternalService/GetUsersByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInternalServiceServer).GetUsersByIDs(ctx, req.(*GetUsersByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInternalService_CheckUserStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInternalServiceServer).CheckUserStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserInternalService/CheckUserStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInternalServiceServer).CheckUserStatus(ctx, req.(*CheckUserStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInternalService_GetSellerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSellerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInternalServiceServer).GetSellerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserInternalService/GetSellerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInternalServiceServer).GetSellerInfo(ctx, req.(*GetSellerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserInternalService_ServiceDesc is the grpc.ServiceDesc for UserInternalService service.
var UserInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserInternalService",
	HandlerType: (*UserInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserBasic",
			Handler:    _UserInternalService_GetUserBasic_Handler,
		},
		{
			MethodName: "GetUsersByIDs",
			Handler:    _UserInternalService_GetUsersByIDs_Handler,
		},
		{
			MethodName: "CheckUserStatus",
			Handler:    _UserInternalService_CheckUserStatus_Handler,
		},
		{
			MethodName: "GetSellerInfo",
			Handler:    _UserInternalService_GetSellerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/user.proto",
}
