// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserBasicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserBasicRequest) Reset()         { *x = GetUserBasicRequest{} }
func (x *GetUserBasicRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *GetUserBasicRequest) ProtoMessage()  {}

func (x *GetUserBasicRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetUserBasicRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserBasicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName   string  `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AvatarUrl  string  `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Role       string  `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Status     string  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TrustScore float64 `protobuf:"fixed64,6,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
}

func (x *UserBasicResponse) Reset()         { *x = UserBasicResponse{} }
func (x *UserBasicResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *UserBasicResponse) ProtoMessage()  {}

func (x *UserBasicResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *UserBasicResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserBasicResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserBasicResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserBasicResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserBasicResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserBasicResponse) GetTrustScore() float64 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

type GetUsersByIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

func (x *GetUsersByIDsRequest) Reset()         { *x = GetUsersByIDsRequest{} }
func (x *GetUsersByIDsRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *GetUsersByIDsRequest) ProtoMessage()  {}

func (x *GetUsersByIDsRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetUsersByIDsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type UsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*UserBasicResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *UsersResponse) Reset()         { *x = UsersResponse{} }
func (x *UsersResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *UsersResponse) ProtoMessage()  {}

func (x *UsersResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *UsersResponse) GetUsers() []*UserBasicResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

type CheckUserStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CheckUserStatusRequest) Reset()         { *x = CheckUserStatusRequest{} }
func (x *CheckUserStatusRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *CheckUserStatusRequest) ProtoMessage()  {}

func (x *CheckUserStatusRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *CheckUserStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IsActive bool   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *UserStatusResponse) Reset()         { *x = UserStatusResponse{} }
func (x *UserStatusResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *UserStatusResponse) ProtoMessage()  {}

func (x *UserStatusResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *UserStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserStatusResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetSellerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetSellerInfoRequest) Reset()         { *x = GetSellerInfoRequest{} }
func (x *GetSellerInfoRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *GetSellerInfoRequest) ProtoMessage()  {}

func (x *GetSellerInfoRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetSellerInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SellerInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShopName     string  `protobuf:"bytes,2,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	ShopSlug     string  `protobuf:"bytes,3,opt,name=shop_slug,json=shopSlug,proto3" json:"shop_slug,omitempty"`
	ShopLogoUrl  string  `protobuf:"bytes,4,opt,name=shop_logo_url,json=shopLogoUrl,proto3" json:"shop_logo_url,omitempty"`
	KycStatus    string  `protobuf:"bytes,5,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	AvgRating    float64 `protobuf:"fixed64,6,opt,name=avg_rating,json=avgRating,proto3" json:"avg_rating,omitempty"`
	TotalReviews int32   `protobuf:"varint,7,opt,name=total_reviews,json=totalReviews,proto3" json:"total_reviews,omitempty"`
}

func (x *SellerInfoResponse) Reset()         { *x = SellerInfoResponse{} }
func (x *SellerInfoResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *SellerInfoResponse) ProtoMessage()  {}

func (x *SellerInfoResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *SellerInfoResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SellerInfoResponse) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *SellerInfoResponse) GetShopSlug() string {
	if x != nil {
		return x.ShopSlug
	}
	return ""
}

func (x *SellerInfoResponse) GetShopLogoUrl() string {
	if x != nil {
		return x.ShopLogoUrl
	}
	return ""
}

func (x *SellerInfoResponse) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

func (x *SellerInfoResponse) GetAvgRating() float64 {
	if x != nil {
		return x.AvgRating
	}
	return 0
}

func (x *SellerInfoResponse) GetTotalReviews() int32 {
	if x != nil {
		return x.TotalReviews
	}
	return 0
}

var _ = reflect.TypeOf
var _ = sync.Mutex{}
